2013-04-06 19:54:23+0000 [-] Log opened.
2013-04-06 19:54:23+0000 [-] twistd 13.0.0 (/usr/bin/python 2.7.3) starting up.
2013-04-06 19:54:23+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2013-04-06 19:54:23+0000 [-] ServerFactory starting on 4000
2013-04-06 19:54:23+0000 [-] Starting factory <twisted.internet.protocol.ServerFactory instance at 0x25cf680>
2013-04-06 19:54:23+0000 [-] Site starting on 8000
2013-04-06 19:54:23+0000 [-] Starting factory <twisted.web.server.Site instance at 0x2600f38>
2013-04-06 19:54:23+0000 [-] Starting factory <src.server.amp.AmpClientFactory instance at 0x2485998>
2013-04-06 19:54:23+0000 [Uninitialized] <twisted.internet.tcp.Connector instance at 0x2600fc8> will retry in 1 seconds
2013-04-06 19:54:23+0000 [Uninitialized] Stopping factory <src.server.amp.AmpClientFactory instance at 0x2485998>
2013-04-06 19:54:25+0000 [-] Starting factory <src.server.amp.AmpClientFactory instance at 0x2485998>
2013-04-06 19:54:25+0000 [Uninitialized] AMPProtocol connection established (HOST:IPv4Address(TCP, '127.0.0.1', 45824) PEER:IPv4Address(TCP, '127.0.0.1', 5000))
2013-04-06 19:54:30+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] /usr/lib/python2.7/site-packages/Django-1.5.1-py2.7.egg/django/conf/urls/defaults.py:3: exceptions.DeprecationWarning: django.conf.urls.defaults is deprecated; use django.conf.urls instead
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::] Traceback (most recent call last):
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::]   File "/home/YourCyborg/evennia/src/players/manager.py", line 35, in func
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::]     players.append(user.get_profile())
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::]   File "/usr/lib/python2.7/site-packages/Django-1.5.1-py2.7.egg/django/contrib/auth/models.py", line 450, in get_profile
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::]     self._state.db).get(user__id__exact=self.id)
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::]   File "/home/YourCyborg/evennia/src/utils/idmapper/manager.py", line 39, in get
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::]     inst = super(SharedMemoryManager, self).get(**kwargs)
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::]   File "/usr/lib/python2.7/site-packages/Django-1.5.1-py2.7.egg/django/db/models/manager.py", line 143, in get
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::]     return self.get_query_set().get(*args, **kwargs)
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::]   File "/usr/lib/python2.7/site-packages/Django-1.5.1-py2.7.egg/django/db/models/query.py", line 389, in get
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::]     (self.model._meta.object_name, kwargs))
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::] DoesNotExist: PlayerDB matching query does not exist. Lookup parameters were {'user__id__exact': 1}
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [EE] No connection User<->Player, maybe database was partially reset?
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::] Traceback (most recent call last):
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::]   File "/home/YourCyborg/evennia/src/players/manager.py", line 35, in func
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::]     players.append(user.get_profile())
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::]   File "/usr/lib/python2.7/site-packages/Django-1.5.1-py2.7.egg/django/contrib/auth/models.py", line 450, in get_profile
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::]     self._state.db).get(user__id__exact=self.id)
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::]   File "/home/YourCyborg/evennia/src/utils/idmapper/manager.py", line 39, in get
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::]     inst = super(SharedMemoryManager, self).get(**kwargs)
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::]   File "/usr/lib/python2.7/site-packages/Django-1.5.1-py2.7.egg/django/db/models/manager.py", line 143, in get
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::]     return self.get_query_set().get(*args, **kwargs)
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::]   File "/usr/lib/python2.7/site-packages/Django-1.5.1-py2.7.egg/django/db/models/query.py", line 389, in get
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::]     (self.model._meta.object_name, kwargs))
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [::] DoesNotExist: PlayerDB matching query does not exist. Lookup parameters were {'user__id__exact': 1}
2013-04-06 19:54:31+0000 [HTTPChannelWithXForwardedFor,0,174.52.125.106] [EE] No connection User<->Player, maybe database was partially reset?
2013-04-06 19:54:38+0000 [-] Received SIGINT, shutting down.
2013-04-06 19:54:38+0000 [AMPProtocol,client] AMPProtocol connection lost (HOST:IPv4Address(TCP, '127.0.0.1', 45824) PEER:IPv4Address(TCP, '127.0.0.1', 5000))
2013-04-06 19:54:38+0000 [AMPProtocol,client] <twisted.internet.tcp.Connector instance at 0x2600fc8> will retry in 1 seconds
2013-04-06 19:54:38+0000 [AMPProtocol,client] Stopping factory <src.server.amp.AmpClientFactory instance at 0x2485998>
2013-04-06 19:54:38+0000 [-] (TCP Port 8000 Closed)
2013-04-06 19:54:38+0000 [-] Stopping factory <twisted.web.server.Site instance at 0x2600f38>
2013-04-06 19:54:38+0000 [-] (TCP Port 4000 Closed)
2013-04-06 19:54:38+0000 [-] Stopping factory <twisted.internet.protocol.ServerFactory instance at 0x25cf680>
2013-04-06 19:54:38+0000 [-] Main loop terminated.
2013-04-06 19:54:38+0000 [-] Server Shut Down.
